### PR TITLE
Title level requests

### PR DESCRIPTION
**Pull request by Dmitriy-Litvinenko**
## Purpose
 * Create title level request checkbox. Refs UIREQ-655.
* Update request results page. Refs UIREQ-614.
* Update request details pane. Refs UIREQ-613.
* Closed TLR should not be able to be duplicated when TLR is disabled. Refs UIREQ-691.
* Update form for possibility of `Title` level requests. Refs UIREQ-620.
* Unchecking the Title level request box when it is automatically checked. Refs UIREQ-633.
* Turn an item level request into a title level request. Refs UIREQ-635.
* View & reorder requests (first accordion). Refs UIREQ-630.
* View & reorder requests (second accordion). Refs UIREQ-644.
* Migrate requests queue/reorder page on new end-points. Refs UIREQ-695.
* Create new request filter. Refs UIREQ-612.
* Change render dependency for item link and information from `requestLevel` to `item`. Refs UIREQ-704.
* Fixed behavior of `hyperlinks` related to `TLR`. Refs UIREQ-702.
* Disable validation on reordering for `Page` requests for `TLR` feature. Refs UIREQ-706.
* Add all required attributes for the `position` field in request info. Refs UIREQ-707.
* The user is redirected to the `Request queue` where the request queue is not displayed. Refs UIREQ-709.
* Select item modal should display all items in the Instance when user uncheck box. Refs UIREQ-700.
* Header and Subhead do not match the given form in Request queue page. Refs UIREQ-713.
* Fulfillment in progress accordion should have position column in Request queue page. Refs UIREQ-705.

## Approach
* This is feature branch for merge all associated commits that was reviewed separately

## Refs
https://issues.folio.org/browse/UXPROD-1796 - Title Level Requests Complete (part 1)
https://issues.folio.org/browse/UIREQ-689

### CODE REVIEW

**Review by Stanislau-Snapok — APPROVED** [review]

**Review by pavelspichonak — APPROVED** [review]

**Comment by mkuklis** [comment]
@Dmitriy-Litvinenko I'm a bit confused here. Is this PR including 19 stories?

**Comment by Dmitriy-Litvinenko** [comment]
@mkuklis Hello, this feature branch that contain all necessary changes for this feature. We already reviewed this pull requests, just for example  https://github.com/folio-org/ui-requests/pull/845

**Review by mkuklis — CHANGES_REQUESTED** [review]
@Dmitriy-Litvinenko bundling everything under one PR makes it harder on many levels and it's a bad practice. I would rather see this being split up into multiple PRs for many reasons:

1) It's much easier to actually perform a code review.
2) If we ever need to chase a bug related to any of these changes it's much easier to go back to a specific commit and be able to figure out what has changed
3) It's really hard to know which part of code is related to which JIRA.

**Comment by mkuklis** [comment]
@Dmitriy-Litvinenko ah never mind. I do see all these issues under `title-level-requests` branch. Ok think I understand the approach you are taking here. It's still going to be harder because all this work will end up under a single commit on master after you squash but I think we should be able to still get to the other history.

**Review by mkuklis — APPROVED** [review]

**Comment by mkuklis** [comment]
@Dmitriy-Litvinenko yes I want to echo what @zburke said. I think the work you, @pavelspichonak and @Stanislau-Snapok is awesome!

**Pull request merged**
