### PR TITLE
UIREQ-760: fix modal appearing for `Restricted` item status

### PR DESCRIPTION
**Pull request by Stanislau-Snapok**
## Purpose
We should show "Request not allowed" modal when creating a request for an item in "Restricted" status.

## Approach
`hasNonRequestableStatus` didn't contain corresponding status.

## Refs
https://issues.folio.org/browse/UIREQ-760

### CODE REVIEW

**Review by Dmitriy-Litvinenko — APPROVED** [review]

**Comment by Dmitriy-Litvinenko** [comment]
Hello @zburke , @mkuklis Could you please review?

**Review by mkuklis — APPROVED** [review]

**Review by artem-blazhko — APPROVED** [review]

**Review by pavelspichonak — APPROVED** [review]

**Review by zburke — APPROVED** [review]

**Review by zburke — CHANGES_REQUESTED** [review]
Do you really want to replace the "creating a new request for an 'available' item" test? 

I think we want to create a new test that checks whether this modal shows up when somebody tries to request a restricted item.

**Comment by Stanislau-Snapok** [comment]
> Do you really want to replace the "creating a new request for an 'available' item" test?
> 
> I think we want to create a new test that checks whether this modal shows up when somebody tries to request a restricted item.

@zburke, for shure! But as you can see I already added `Restricted` status into `nonRequestableItemStatuses` in `test/bigtest/tests/new-request-test.js` file. Below we have construction `nonRequestableItemStatuses.forEach(status ...` that creates bunch of tests for `error modal` for each unrequestable status.

**Review by zburke — APPROVED** [review]
@Stanislau-Snapok, ah, yeah, I see. I just got confused looking at the diff and only seeing part of the file. My bad!

**Comment by Stanislau-Snapok** [comment]
Original bug was closed as "won't do". I'm closing this pull request.

**Pull request closed without merging**
